"""
.. module:: gendir.py
    :synopsis: Useful module to generate the directory if not exists.

.. moduleauthor:: Arulalan.T <arulalant@gmail.com>
"""

import os


def createDirIfNotExists(dirpath, subdir):
    """
    :func:`createDirIfNotExists` : It should create the directory if the
            passed path is not exists.

    Inputs : The dirpath arg is an absolute path only.
             subdir is the sub directory name to create it under the dirpath.

    Condition : It can create the subdir directory in the path, if that is
                not exists. It can not create multilevel directories. And it
                can not create the root dirpath.

    Outputs : If it will create new directory means, it should print the
              message about the newly created directory with passed arg.
              And it should return the path, which has generated by combining
              the dirpath and subdir together.
    """

    dirpath = os.path.join(dirpath, subdir)
    if not os.path.isdir(dirpath):
        os.mkdir(dirpath)
        print "Created directory : %s" % (dirpath)
    return dirpath
# end of def createDirIfNotExists(dirPath):

def createDirsIfNotExists(dirpath, subdir):
    """
    :func:`createDirsIfNotExists` : It should create the directory if the
            passed path is not exists.

    Inputs : The dirpath arg is an absolute path only.
             subdir is the sub directory name to create it under the dirpath.

    Condition : It can create the subdir directory in the path, if that is
                not exists. If the subdir arg is string means, it should
                create that directory name under the root dirPath.
                It can create multilevel directories. If subdir is list or
                tuple which consits the str names, then it should create those
                sub directories in those order itself under the root dirpath.
                It can not create the root dirpath.

    Outputs : If it will create new directory means, it should print the
              message about the newly created directory with passed arg.
              And it should return the final path of the subdir in the passed
              list, which has generated by combining the dirpath and sub
              directories together.

    Date : 14.10.2011

    """

    if isinstance(subdir, str):
        return createDirIfNotExists(dirpath, subdir)

    elif isinstance(subdir, (list, tuple)):
        for dirname in subdir:
            dirpath = createDirIfNotExists(dirpath, dirname)
        return dirpath
    else:
        raise TypeError('subdir is must either str or list or tuple only')
# end of def createDirsIfNotExists(dirpath, subdir):
